### PR TITLE
SPDX and foundation setup

### PR DESCRIPTION
**Pull request by lsf37**

### CODE REVIEW

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Review by kent-mcleod — APPROVED** [review]

**Comment by lsf37** [comment]
Sorry for the base branch noise, I was trying to get the CI to see the updated master branch, which it now does.

**Comment by ssrg-bamboo** [comment]
## Test results for commit b68a57fa6e8d04f956f5e0fa597dcb353ea8a1a6

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - camkes-manifest - EXT-seL4-spdx-6 | FAILED |
| Code Quality - Style - camkes-manifest - EXT-seL4-spdx-6 | SUCCESSFUL |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Check licenses - camkes-manifest - EXT-seL4-spdx-6 | Check licenses | 1 of 1 job failed |

**Job: lic**
Build logs

    02-Dec-2020 15:04:25	Build Code Quality - Check licenses - camkes-manifest - EXT-seL4-spdx-6 - lic #1 (CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ-1) started building on agent A local agent 1, bamboo version: 7.1.4
    02-Dec-2020 15:04:25	I run on the Bamboo server!
    02-Dec-2020 15:04:25	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ
    02-Dec-2020 15:04:25	Executing build Code Quality - Check licenses - camkes-manifest - EXT-seL4-spdx-6 - lic #1 (CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ-1)
    02-Dec-2020 15:04:25	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ/. (location: .)
    02-Dec-2020 15:04:25	Artifact 'code' prepared in 9.247 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ/./code.tar.gz
    02-Dec-2020 15:04:25	Running pre-build action: VCS Version Collector
    02-Dec-2020 15:04:25	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Dec-2020 15:04:25	+ tar xf code.tar.gz --recursive-unlink
    02-Dec-2020 15:04:25	Finished task 'Untar code' with result: Success
    02-Dec-2020 15:04:25	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Dec-2020 15:04:25	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ
    02-Dec-2020 15:04:25	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    02-Dec-2020 15:04:25	Starting task 'Check license' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Dec-2020 15:04:25	+ python license-tool/check_license.py camkes-manifest
    02-Dec-2020 15:04:25	ERROR:root:camkes-manifest/README.md: camkes-manifest/README.md: no owner found
    02-Dec-2020 15:04:25	ERROR:root:camkes-manifest/default.xml: camkes-manifest/default.xml: no owner found
    02-Dec-2020 15:04:25	ERROR:root:camkes-manifest/l4v-master.xml: camkes-manifest/l4v-master.xml: no owner found
    02-Dec-2020 15:04:25	ERROR:root:camkes-manifest/master.xml: camkes-manifest/master.xml: no owner found
    02-Dec-2020 15:04:25	ERROR:root:camkes-manifest/working.xml: camkes-manifest/working.xml: no owner found
    02-Dec-2020 15:04:25	ERROR:root:camkes-manifest/.github/CODE_OF_CONDUCT.md: camkes-manifest/.github/CODE_OF_CONDUCT.md: no owner found
    02-Dec-2020 15:04:25	ERROR:root:camkes-manifest/.github/CONTRIBUTING.md: camkes-manifest/.github/CONTRIBUTING.md: no owner found
    02-Dec-2020 15:04:25	ERROR:root:camkes-manifest/.github/workflows/pr.yml: camkes-manifest/.github/workflows/pr.yml: no owner found
    02-Dec-2020 15:04:25	ERROR:root:camkes-manifest/.github/workflows/push.yml: camkes-manifest/.github/workflows/push.yml: no owner found
    02-Dec-2020 15:04:25	ERROR:root:camkes-manifest/snapshots/snapshot-20150518171951.xml: camkes-manifest/snapshots/snapshot-20150518171951.xml: no owner found
    02-Dec-2020 15:04:25	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ-1-ScriptBuildTask-11397560562258240.sh] was 1 while expected 0
    02-Dec-2020 15:04:25	Finished task 'Check license' with result: Failed
    02-Dec-2020 15:04:25	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Dec-2020 15:04:25	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ
    02-Dec-2020 15:04:25	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    02-Dec-2020 15:04:25	Running post build plugin 'NCover Results Collector'
    02-Dec-2020 15:04:25	Running post build plugin 'Artifact Copier'
    02-Dec-2020 15:04:25	Running post build plugin 'npm Cache Cleanup'
    02-Dec-2020 15:04:25	Running post build plugin 'Clover Results Collector'
    02-Dec-2020 15:04:25	Running post build plugin 'Docker Container Cleanup'
    02-Dec-2020 15:04:25	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ'
    02-Dec-2020 15:04:25	Finalising the build...
    02-Dec-2020 15:04:25	Stopping timer.
    02-Dec-2020 15:04:25	Build CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ-1 completed.
    02-Dec-2020 15:04:25	Running on server: post build plugin 'NCover Results Collector'
    02-Dec-2020 15:04:25	Running on server: post build plugin 'Build Hanging Detection Configuration'
    02-Dec-2020 15:04:25	Running on server: post build plugin 'Clover Delta Calculator'
    02-Dec-2020 15:04:25	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    02-Dec-2020 15:04:25	All post build plugins have finished
    02-Dec-2020 15:04:25	Generating build results summary...
    02-Dec-2020 15:04:25	Saving build results to disk...
    02-Dec-2020 15:04:25	Store variable context...
    02-Dec-2020 15:04:25	Indexing build results...
    02-Dec-2020 15:04:25	Finished building CQ-CAMKESMANIFESTCL15-CAMKESMANIFESTLICCQ-1.


This is the most I can report on right now, sorry!

**Comment by lsf37** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by lsf37** [comment]
Merged in 7e3fddc

**Pull request closed without merging**
